### PR TITLE
XT-3054 Workiva build fixes

### PR DESCRIPTION
**Pull request by austinmatherne-wk**
#### Description of change
Python package version detection inspects the working directory for uncommitted changes.
If there are uncommitted changes the build is determined to be a dev build. For the workiva
docker build this causes it to always be dirty because tracked files are excluded from the
build environment.

Additionally updates the Python version and includes the package lock file for the docker build.

#### Steps to Test
* CI

**review**:
@Workiva/xt
@paulwarren-wk

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by derekgengenbacher-wf — APPROVED** [review]
Nice. I was going to ask if we could upgrade this to 3.11.

**Comment by derekgengenbacher-wf** [comment]
QA +10 Unit and Skynet tests pass successfully. Builds successfully.

@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
