### PR TITLE
XT-1491 - Add ranges to dependencies

### PR DESCRIPTION
**Pull request by derekgengenbacher-wf**
#### Description:
- Add ranges to dependencies to reduce possible downstream dependency conflicts.

#### Testing:
- CI

**review**:
@Workiva/xt

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by sagesmith-wf — APPROVED** [review]
Do you know if dependabot handles this?

**Review by austinmatherne-wk — APPROVED** [review]

**Comment by austinmatherne-wk** [comment]
### Verified

* ci

QA +10
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
