### PR TITLE
Fix truncation

### LINKED ISSUE #347: BUG: Footnote text is truncated no-matter how big the window is
### Description
The footnote text is truncated no-mater how big the window is

Screen Shot 2022-12-06 at 4 37 58 PM

@Workiva/xt @paulwarren-wk

### PR DESCRIPTION
**Pull request by sagesmith-wf**
### Description
Fixes #347 

@Workiva/xt @paulwarren-wk

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by paulwarren-wk** [comment]
https://github.com/sagesmith-wf/ixbrl-viewer/pull/1

**Review by aaroncameron-wk — DISMISSED** [review]

**Comment by sagesmith-wf** [comment]
> Tests added here: https://github.com/sagesmith-wf/ixbrl-viewer/pull/1

Thanks Paul, I pulled them!

**Review by aaroncameron-wk — APPROVED** [review]

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
