### PR TITLE
Design updates

### PR DESCRIPTION
**Pull request by pdw-mb**
This PR implements the public viewer portion of the design updates described on XT 1164.

Specifically:
* Document title realigned to the left
* Addition of a key to colors used in the document (mouseover "?" icon)

Note that in the public viewer, colors are used to differentiate namespaces.

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by brettkail-wk — APPROVED** [review]

**Review by derekgengenbacher-wf — APPROVED** [review]

**Review by austinmatherne-wk — APPROVED** [review]

**Comment by derekgengenbacher-wf** [comment]
QA +10 Unit tests pass successfully. Builds successfully. Built locally and viewed changes successfully.

@Workiva/release-management-p

**Comment by colefeisthamel-wf** [comment]
RM +1 merging per teams request.

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
