### PR TITLE
Fix error trying to get a prefix for a footnote

### LINKED ISSUE #427: [BUG] Search indexing fails if table fact includes footnote
### What happened?

Search indexing appears to fail at startup If a fact contained in a table cell includes a footnote.

``` javascript
ixbrlviewer.js:2 Uncaught TypeError: e.getConceptPrefix is not a function
    at ixbrlviewer.js:2:1824828
    at Array.map (<anonymous>)
    at Qt.getUsedPrefixes (ixbrlviewer.js:2:1824818)
    at In.setupSearchControls (ixbrlviewer.js:2:1866884)
    at In.searchReady (ixbrlviewer.js:2:1867702)
    at ixbrlviewer.js:2:1862768
    at hn.buildSearchIndex (ixbrlviewer.js:2:1845996)
    at buildSearchIndex.next (<anonymous>)
    at t (ixbrlviewer.js:2:1813312)
```

### Version

1.1.70

### With which browsers are you experiencing the bug?

Firefox, Chrome, Safari

### Documents

[Footnote_Bug.zip](https://github.com/Workiva/ixbrl-viewer/files/11508821/Footnote_Bug.zip)

### Screenshots

Screen Shot 2023-05-18 at 10 11 35 AM
Screen Shot 2023-05-18 at 10 11 47 AM

### PR DESCRIPTION
**Pull request by paulwarren-wk**
#### Reason for change

Fixes #427

#### Description of change

Adds a guard in two places to check that item (which can be a footnote or a fact) is actually a fact before attempting to get the namespace prefix.

#### Steps to Test

* Open sample doc from #427 
* Confirm that there are no errors in the log.

**review**:
@Workiva/xt
@paulwarren-wk

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Comment by paulwarren-wk** [comment]
Bumping back to draft, as I want to investigate a little bit more.

**Comment by paulwarren-wk** [comment]
> Bumping back to draft, as I want to investigate a little bit more.

Ready.  I misunderstood the problem.  The search index is already just facts (not footnotes), but the code to get used prefixes and units was not.

**Review by brettkail-wk — APPROVED** [review]

**Review by allenbross-wf — APPROVED** [review]

**Review by aaroncameron-wk — APPROVED** [review]

**Review by sagesmith-wf — APPROVED** [review]

**Review by sagesmith-wf — APPROVED** [review]
QA +10

- Fixes test that noticed the issue

**Comment by sagesmith-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
