### PR TITLE
Highlighting CSS fixes

### PR DESCRIPTION
**Pull request by paulwarren-wk**
#### Reason for change

Fixes two highlighting related issues:

1. Where a tagged element has zero size (usually because the only content is absolutely positioned elements), we add an `ixbrl-no-highlight` class to avoid putting a border around it when the fact is selected.  We previously weren't filtering on this when highlighting related facts.  For example, when mouse-overing the "associated facts" section of footnote.
2. We apply a different outline offset to table cells (-1px) from other content (+1px).  Due to a CSS priority issue, this wasn't being applied correctly when highlighting related items in a calculation:

image

(note green outlines are larger than blue outline)

#### Description of change

1. Is fixed by adding `:not(.ixbrl-no-highlight)` in additional places.
2. Is fixed by adding `:not(td, th)` on the default outline offset declaration.

#### Steps to Test

1. Requires a document with an element with absolutely positioned children and a footnote.  Select the footnote, and then mouseover the fact in the "associated facts" section.
2. Requires a document with a calculation where the contributing facts are in table cells.  Select the total, and check the size of the green dotted outline of the contributing facts.

**review**:
@Workiva/xt
@paulwarren-wk

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by brettkail-wk — APPROVED** [review]

**Review by sagesmith-wf — APPROVED** [review]

**Review by austinmatherne-wk — APPROVED** [review]

**Review by sagesmith-wf — COMMENTED** [review]
@paulwarren-wk would it be possible for you to supply a document for QA?

**Comment by paulwarren-wk** [comment]
@sagesmith-wf see attached.  Click on the total/sub total rows to see item (2).  Click on the "This is a footnote" text, and the mouse over the "Associated facts" to see item (1).

[pr391.zip](https://github.com/Workiva/ixbrl-viewer/files/10913737/pr391.zip)

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
